### ISSUE TITLE
Found 'nan' value in the label of the data

### ISSUE THREAD

**Issue by QingyongHu** [WeikaiTan/Toronto-3D#1]
Hi @WeikaiTan, thanks for your efforts in this area!
However, I just found there is a series of `nan` value in the label of the data, can you please check the label value of the dataset?

I just use np.unique(labels) and found the following results:
![image](https://user-images.githubusercontent.com/29670234/77262942-abb2d080-6c8e-11ea-9aa7-a39a8d1f0fbf.png)

Many thanks!

**Comment by WeikaiTan** [comment]
Thanks for your feedback. I’m aware that there are a small number of points were missed during the labelling process, and I treat them as unclassified. I’ll update the dataset to remove these points to make it easier to use.
