### ISSUE TITLE
Bug in L003.ply

### ISSUE THREAD

**Issue by zcy1065670505** [WeikaiTan/Toronto-3D#7]
Hi
I found some bug in L003.ply when I use plyfile to read L003.ply.  much intensity of some points are NaN。 Codes are follows:

plydata = PlyData.read(filename)
pc = plydata['vertex'].data
pc_array = np.array([i.tolist() for i in pc ])

**Comment by WeikaiTan** [comment]
There are some points missing intensity or RGB or labels, but they shouldn't have a large volume. You can treat them as noise and discard them during processing.
