### ISSUE TITLE
Example DataLoader

### ISSUE THREAD

**Issue by ycjing** [WeikaiTan/Toronto-3D#8]
Hi @WeikaiTan 

Thank you for this great dataset! I wonder if there are any examples for loading and using the dataset?

Best,
Yongcheng

**Comment by WeikaiTan** [comment]
There are different ways of loading the dataset depending on the method applied. You may check out the implementation of Open3D-ML https://github.com/intel-isl/Open3D-ML

**Comment by ycjing** [comment]
Hi @WeikaiTan 

Thank you for the quick response! I appreciate it. I will have a try.

Best,
Yongcheng
